mkl:
  - 2025

blas_impl:
  - mkl                        # [(x86 or x86_64) and not osx]
  - openblas

fortran_compiler:
  - flang             # [win]
fortran_compiler_version:
  - 20                # [win]