{% set version = "4.5.4" %}
{% set version_win = "a0e1db7f2de7bdc456648d8d0816f5273afaf3e7" %}

{% set variant = "openblas" %}

package:
  name: suitesparse
  version: {{ version }}

source:
  fn: SuiteSparse-{{ version }}.tar.gz
  url: http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-{{ version }}.tar.gz  # [not win]
  sha256: 698b5c455645bb1ad29a185f0d52025f3bd7cb7261e182c8878b0eb60567a714  # [not win]
  url: https://github.com/jlblancoc/suitesparse-metis-for-windows/archive/{{ version_win }}.tar.gz  # [win]
  sha256: 719065607201f445d490b6bb7bb43df2e8f1affb187551c841d5d2a3dd72f2e7  # [win]
  patches:
    - gh_53.patch  # [win]
    - gh_54.patch  # [win]

build:
  skip: true  # [win32]
  number: 201
  features:
    - blas_{{ variant }}
    - vc14    # [win]
  msvc_compiler: 14.0

requirements:
  build:
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - tbb
    - cmake
    - metis 5.1.*
    - ninja  # [win]
    - vc 14  # [win]

  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - tbb
    - metis 5.1.*
    - vc 14  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libamd${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libbtf${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libcamd${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libccolamd${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libcholmod${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libcolamd${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libcxsparse${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libklu${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libldl${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/librbio${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libspqr${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libsuitesparseconfig${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libumfpack${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libamd.a  # [not win]
    - test -f ${PREFIX}/lib/libbtf.a  # [not win]
    - test -f ${PREFIX}/lib/libcamd.a  # [not win]
    - test -f ${PREFIX}/lib/libccolamd.a  # [not win]
    - test -f ${PREFIX}/lib/libcholmod.a  # [not win]
    - test -f ${PREFIX}/lib/libcolamd.a  # [not win]
    - test -f ${PREFIX}/lib/libcxsparse.a  # [not win]
    - test -f ${PREFIX}/lib/libklu.a  # [not win]
    - test -f ${PREFIX}/lib/libldl.a  # [not win]
    - test -f ${PREFIX}/lib/librbio.a  # [not win]
    - test -f ${PREFIX}/lib/libspqr.a  # [not win]
    - test -f ${PREFIX}/lib/libsuitesparseconfig.a  # [not win]
    - test -f ${PREFIX}/lib/libumfpack.a  # [not win]

    - conda inspect linkages -p ${PREFIX} suitesparse  # [not win]
    - conda inspect objects -p ${PREFIX} suitesparse  # [osx]

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: LGPL v2 (AMD, BTF, etc), BSD 3-clause (UFget), GPL v2 (UMFPACK, RBIO, SPQR, GPUQRENGINE), Apache 2.0 (Metis)
  summary: A suite of sparse matrix algorithms

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
