{% set version = "7.0.1" %}

package:
  name: suitesparse
  version: {{ version }}

source:
  - url: https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v{{ version }}.tar.gz
    sha256: dc2f8d5c2657c120b30cce942f634ec08fc3a4b0b10e19d3eef7790b2bec8d1e

build:
  number: 0
  skip: True  # [s390x]
  run_exports:
    - {{ pin_subpackage("suitesparse") }}
  missing_dso_whitelist:
    - '*/libomp.dylib'    # [osx]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - cmake
    - ninja-base
    - make  # [unix]
  host:
    # UMFPACK, CHOLMOD, and SPQR
    - mkl-devel  {{ mkl }}            # [blas_impl == 'mkl']
    - openblas-devel {{ openblas }}   # [blas_impl == "openblas"]
    - tbb-devel 2021.8.0
    # SPEX
    - mpfr 4.0.2                      # [not win]
    - gmp 6.2.1                       # [not win]
    # OpenMP
    # For openblas on win and linux, we don't specify any openmp implementation; it comes from the compiler.
    - llvm-openmp 14.0.6              # [osx]
    - intel-openmp   {{ mkl }}        # [blas_impl == 'mkl']
  run:
    - mpfr >=4.0.2,<5.0a0             # [not win]
    - gmp >=6.2.1,<7.0a0              # [not win]
    - _openmp_mutex                   # [linux]

test:
  commands:
    # Verify libraries.
    {% set libs = [
            "amd",
            "btf",
            "camd",
            "ccolamd",
            "cholmod",
            "colamd",
            "cxsparse",
            "klu",
            "ldl",
            "rbio",
            "spqr",
            "suitesparseconfig",
            "umfpack"
    ] %}
    {% if unix %}
    {% for lib in libs %}
    - test -f ${PREFIX}/lib/lib{{ lib }}${SHLIB_EXT}
    - test -f ${PREFIX}/lib/lib{{ lib }}.a
    {% endfor %}
    {% else %}
    {% for lib in libs %}
    - IF NOT EXIST %LIBRARY_BIN%\{{ lib }}.dll exit 1
    - IF NOT EXIST %LIBRARY_LIB%\{{ lib }}.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\{{ lib }}_static.lib exit 1
    {% endfor %}
    {% endif %}

about:
  home: https://people.engr.tamu.edu/davis/suitesparse.html
  license: LGPL-2.1-or-later AND BSD-3-Clause AND GPL-2.0-or-later AND Apache-2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: A suite of sparse matrix algorithms
  description: A suite of sparse matrix algorithms
  dev_url: https://github.com/DrTimothyAldenDavis/SuiteSparse
  doc_url: https://github.com/DrTimothyAldenDavis/SuiteSparse

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
    - cbouss
