{% set version = "7.8.3" %}

package:
  name: suitesparse
  version: {{ version }}

source:
  - url: https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v{{ version }}.tar.gz
    sha256: ce39b28d4038a09c14f21e02c664401be73c0cb96a9198418d6a98a7db73a259

build:
  number: 0
  skip: True  # [s390x]
  run_exports:
    - {{ pin_subpackage("suitesparse") }}
  missing_dso_whitelist:
    - '*/libomp.dylib'    # [osx]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    # Upstream has checks that disable import library creation on Windows for newer CMake versions.
    # https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/v7.8.3/SuiteSparse_config/CMakeLists.txt#L189
    - cmake <3.25
    - ninja-base
    - make  # [unix]
  host:
    # UMFPACK, CHOLMOD, and SPQR
    - mkl-devel {{ mkl }}             # [blas_impl == 'mkl']
    - openblas-devel {{ openblas }}   # [blas_impl == "openblas"]
    - tbb-devel 2022.0.0
    # SPEX
    - mpfr {{ mpfr }}
    - gmp {{ gmp }}
    # OpenMP
    # For openblas on win and linux, we don't specify any openmp implementation; it comes from the compiler.
    - llvm-openmp 14.0.6              # [osx]
    - intel-openmp {{ mkl }}          # [blas_impl == 'mkl']
  run:
    - _openmp_mutex                   # [linux]
    - intel-openmp {{ mkl }}          # [blas_impl == 'mkl']

test:
  commands:
    # Verify libraries.
    {% set libs = [
            "amd",
            "btf",
            "camd",
            "ccolamd",
            "cholmod",
            "colamd",
            "cxsparse",
            "klu",
            "ldl",
            "paru",
            "rbio",
            "spqr",
            "suitesparseconfig",
            "umfpack"
    ] %}
    {% if unix %}
    {% for lib in libs %}
    - test -f ${PREFIX}/lib/lib{{ lib }}${SHLIB_EXT}
    - test -f ${PREFIX}/lib/lib{{ lib }}.a
    {% endfor %}
    {% else %}
    {% for lib in libs %}
    - IF NOT EXIST %LIBRARY_BIN%\{{ lib }}.dll exit 1
    - IF NOT EXIST %LIBRARY_LIB%\{{ lib }}.lib exit 1
    - IF NOT EXIST %LIBRARY_LIB%\{{ lib }}_static.lib exit 1
    {% endfor %}
    {% endif %}

about:
  home: https://people.engr.tamu.edu/davis/suitesparse.html
  license: LGPL-2.1-or-later AND BSD-3-Clause AND GPL-2.0-or-later AND Apache-2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: A suite of sparse matrix algorithms
  description: A suite of sparse matrix algorithms
  dev_url: https://github.com/DrTimothyAldenDavis/SuiteSparse
  doc_url: https://github.com/DrTimothyAldenDavis/SuiteSparse

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
    - cbouss
