{% set version = "4.5.3" %}

{% set variant = "openblas" %}

{% set dyn_ext = ".so" %}  # [linux]
{% set dyn_ext = ".dylib" %}  # [osx]


package:
  name: suitesparse
  version: {{ version }}

source:
  fn: SuiteSparse-{{ version }}.tar.gz
  url: http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-{{ version }}.tar.gz
  sha256: 6199a3a35fbce82b155fd2349cf81d2b7cddaf0dac218c08cb172f9bc143f37a
  patches:
    - SPQR_TBB.patch

build:
  skip: true  # [win]
  number: 200
  features:
    - blas_{{ variant }}

requirements:
  build:
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - tbb
    - cmake

  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - tbb

test:
  commands:
    - test -f ${PREFIX}/lib/libamd{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libbtf{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libcamd{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libccolamd{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libcholmod{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libcolamd{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libcxsparse{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libklu{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libldl{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libmetis{{ dyn_ext }}
    - test -f ${PREFIX}/lib/librbio{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libspqr{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libsuitesparseconfig{{ dyn_ext }}
    - test -f ${PREFIX}/lib/libumfpack{{ dyn_ext }}

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: LGPL v2 (AMD, BTF, etc), BSD 3-clause (UFget), GPL v2 (UMFPACK, RBIO, SPQR, GPUQRENGINE), Apache 2.0 (Metis)
  summary: A suite of sparse matrix algorithms

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
